# GitLab CI/CD para GitLab Pages
# Este archivo configura el pipeline para construir y desplegar la aplicación React

# Definir las etapas del pipeline
stages:
  - build
  - deploy

# Variables globales
variables:
  # Directorio donde se construye la aplicación
  PUBLIC_URL: "/afs"
  # Directorio de salida para GitLab Pages
  GIT_DEPTH: 0

# Trabajo de construcción
build:
  stage: build
  image: node:18-alpine
  
  # Cache para node_modules (opcional pero recomendado)
  cache:
    paths:
      - node_modules/
  
  # Scripts a ejecutar
  script:
    - npm ci --only=production
    - npm run build
    
  # Artefactos a guardar
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
    
  # Solo ejecutar en rama main/master
  only:
    - main
    - master

# Trabajo de despliegue a GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  
  # Dependencias del trabajo de build
  dependencies:
    - build
    
  script:
    # Instalar git
    - apk add --no-cache git
    # Mover archivos construidos al directorio public
    - mkdir public
    - cp -r build/* public/
    # Crear archivo .gitlab-ci.yml en public para evitar conflictos
    - echo "pages" > public/.gitlab-ci.yml
    
  artifacts:
    paths:
      - public
    expire_in: 1 hour
    
  # Solo ejecutar en rama main/master
  only:
    - main
    - master
